version: "3.8"

services:
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=dispenser
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - "27017-27019:27017-27019"
    expose:
      - 27017-27019 
    volumes:
      - ./ops/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      # - ./mongo-volume:/data/db
    healthcheck:
      test: "exit 0"

  redis:
    image: 'redis:latest'
    container_name: 'redis'
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - ./ops/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: "exit 0"

